### ISSUE TITLE
[V2]

### ISSUE THREAD

**Issue by markboulton** [alecritson/Placid-Statamic#12]
Following the docs, I've added the following to my templates:

```{{ placid:request access_token="weather" handle="weather_api" }}
{{ if no_results }}
   No results
{{ else }}
{{ weather }}
  {{ main }}
{{ /weather }}
{{ endif }}
{{ /placid:request }}

And my config file:

placid_tokens:
  weather: ############

weather_api:
  url: 'http://api.openweathermap.org/data/2.5/weather'
  query:
    q: 'London,uk'
```

The request shows 'no results' rendered in the browser. I've checked my key and it's right. I then created another test with jsonplaceholder to make sure it wasn't my mistake and, again, the api call fails. Any ideas?

**Comment by alecritson** [comment]
Do you have an example of what comes back from the api itself?

I have been working on a big update for this plugin which should address a bunch of issues people have been having. But I can look into this later to try and get a fix our

**Comment by alecritson** [comment]
Do you have an example of what comes back from the api itself?

I have been working on a big update for this plugin which should address a bunch of issues people have been having. But I can look into this later to try and get a fix out

**Comment by alecritson** [comment]
Do you have an example of what comes back from the api itself?

I have been working on a big update for this plugin which should address a bunch of issues people have been having. But I can look into this later to try and get a fix out

**Comment by alecritson** [comment]
Do you have an example of what comes back from the api itself?

I have been working on a big update for this plugin which should address a bunch of issues people have been having. But I can look into this later to try and get a fix out

**Comment by markboulton** [comment]
Thanks Alec. There's nothing coming back from the API at all. Seems to be failing there. Is there anything else I can give you more specific that might help? From the logs, or putting in a line of code in the add-on? Just let me know. Happy to help out.

**Comment by markboulton** [comment]
Oh, sorry, I think I misunderstood your question. This is an example of the data that should come back:

```
{
"coord":{"lon":-0.13,"lat":51.51},
"weather":[{"id":300,"main":"Drizzle","description":"light intensity
drizzle","icon":"09d"}],
"base":"stations",
"main":{"temp":280.32,"pressure":1012,"humidity":81,"temp_min":279.15,"temp_max":281.15},
"visibility":10000,
"wind":{"speed":4.1,"deg":80},
"clouds":{"all":90},
"dt":1485789600,
"sys: {"type":1,"id":5091,"message":0.0103,"country":"GB","sunrise":1485762037,"sunset":1485794875},
"id":2643743,
"name":"London",
"cod":200
}```

See, here: http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b6907d289e10d714a6e88b30761fae22

**Comment by alecritson** [comment]
Hey @markboulton 

I think I found the issue, the query string wasn't being sent to the client when used in a request context. I've pushed a fix so make sure you update the plugin.

Also, the weather API doesn't use `access_token` as a query parameter so my config actually ended up looking like this:

```
weather_api:
  url: 'http://api.openweathermap.org/data/2.5/weather'
  query:
    q: London,uk
    APPID: <token>
```

> Notice there are no single quotes `'` wrapping the string

And lastly, my template ended up looking like this: (note it's wrapped in a request tag, this is a workaround that will be resolved in the next statamic update)

```
{{ placid:request handle="weather_api" }}
    {{ if no_results }} 
        No results 
    {{ else }} 
        {{ response }}
            {{ weather }} {{ main }} {{ /weather }}
        {{ /response }}
    {{ endif }}
{{ /placid:request }}
```
That gave me the response `clouds`. If you ever get any issues with the requests not coming back, you can always do `dd($e)` on line 88 of `PlacidTags.php` and this will give you an idea of anything going wrong (just remember to comment out the caching part lines 69 > 75)

Hopefully, that will sort you out, any problems just reopen the issue.

**Comment by markboulton** [comment]
Brilliant. Thanks @alecritson - that works perfectly now.
