### ISSUE TITLE
Placid with Laravel Blade template

### ISSUE THREAD

**Issue by mschlosser22** [alecritson/Placid-Statamic#16]
I'm currently using Laravel Blade template in Statamic instead of the Antlers templates. How would I reproduce the following in a Blade template:

{{ placid:request url="http://someurl.ngrok.io/api/form/9" cache="0" refresh="1200" }}
    {{ response }}
    {{ /response }}
{{ /placid:request }}

**Comment by alecritson** [comment]
I'm not entirely sure to be honest. I've never tried to use Statamic in that way before and I don't think this is specifically related to the plugin. It'd be best to check out the docs and/or ask on the Slack channel.
