### ISSUE TITLE
Example to make Post Request

### ISSUE THREAD

**Issue by kodeine** [alecritson/Placid-Statamic#17]
Hello,
is it possible to make a post request to the API?

**Comment by alecritson** [comment]
Hey @kodeine 

You should be able to just specify the method as a parameter, 

```
{{ placid:request url="http://someapi.com" cache="0" refresh="1200" method="POST"  }}
{{ /placid:request }}
```
If you're talking about form based submissions, currently this is unsupported, but in the pipeline

**Comment by kodeine** [comment]
awesome! i was looking for form based submission.
