### ISSUE TITLE
How to make nested placid calls?

### ISSUE THREAD

**Issue by tcagkansokmen** [alecritson/Placid-Statamic#18]
Hello,

I can't make nested statamic calls.

`{{ placid:request method="get" url="https://jsonplaceholder.typicode.com/posts" cache="0" refresh="1200" }}
{{ response }}
{{ placid:request method="get" url="https://jsonplaceholder.typicode.com/post/{{ postId }}" cache="0" refresh="1200" }}
{{ response }}
deneme
{{ /response }}
 {{ /placid:request }}
{{ /response }}
 {{ /placid:request }}`

but when i try, that doesnt work. 

the result works like;
{{ /response }} {{ /placid:request }}

how can I resolve that?

**Comment by alecritson** [comment]
I'll try and take a look at this as soon as I can. What version of Statamic are you using?

**Comment by tcagkansokmen** [comment]
hello,

2.10.3
 
thanks for your support.

**Comment by alecritson** [comment]
Looks like this might be a statamic limitation at the moment, will look into it for future releases though.

**Comment by sebszocinski** [comment]
+1 this is still an issue for me... any chance of this being fixed?
