### ISSUE TITLE
Can't use variables

### ISSUE THREAD

**Issue by tcagkansokmen** [alecritson/Placid-Statamic#19]
Here is my code:
id comes from other placid with loop. And i want to use that as like examples.
But when I use like that;
`{{ placid:request method="get" handle="apiv2" path="/{{ id }}" cache="0" refresh="1200" }}
                                                                {{ /placid:request }}`

It turns me a broken url like (below id, all the data is html)

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3479434/45672793-bccad080-bb31-11e8-8d21-6f1bf4c8a316.png">

**Comment by alecritson** [comment]
Thanks for the info, I will take a look as soon as I can. What version of Statamic are you using?

**Comment by tcagkansokmen** [comment]
hello,

version is: 2.10.3
 
thanks for your support.

**Comment by alecritson** [comment]
Hi There,

Not sure if this is still an issue, I thought it was a limitation of Statamic but you should be able to do this using single brackets `{` instead of the double `{{`, according to the docs:

https://docs.statamic.com/antlers#vars-in-params
