### ISSUE TITLE
v2 versus v3

### ISSUE THREAD

**Issue by gildotdev** [alecritson/Placid-Statamic#24]
I went try out this add on from t[he marketplace ](https://statamic.com/marketplace/addons/placid) and it says there that it requires Statamic V2 but when I try to install via composer it says it requires V3. Is there a way to use the V2 version since V3 is still in beta?

Thanks!

**Comment by alecritson** [comment]
Hey @gilcreque yes you can use the V2 branch and readme :)any problems give me a shout
