### ISSUE TITLE
Statamic v3 - how did you get it to work?

### ISSUE THREAD

**Issue by bzerangue** [alecritson/Placid-Statamic#25]
@alecritson - First off, thank you so much for this add-on! It is an indispensable add-on. It is extremely helpful. 

I installed it... `composer require ritson/placid-statamic` and then ran `composer update`.

I am trying to get this work. Actually, when I installed it on Statamic v3, it doesn't show up as installed under "Installed Add-ons".

And it doesn't work on the page. It is just ignored. Any ideas on how I can get this running with Statamic v3?

**Comment by bzerangue** [comment]
@alecritson - have you been able to get Placid-Statamic to work with Statamic 3?

**Comment by alecritson** [comment]
@bzerangue - Just just pushed an update to 3.0.1 which should get this installable for you. I've tested with a basic example from the readme.

```
{{ placid host="https://jsonplaceholder.typicode.com" path=":part/:id" cache="60" query="foo:bar|bar:baz" segments="part:posts|id:1" headers="foo:bar" }}
  {{ response.data }}
    <h1>{{ title }}</h1>
  {{ /response.data }}
{{ /placid }}
```

And it looks like it was returning the content. I'll close this for now, if you still get issues let me know. If they aren't related to installing just open another issue :)
