### ISSUE TITLE
Use another parameter for authentication?

### ISSUE THREAD

**Issue by seanwash** [alecritson/Placid-Statamic#4]
Hey there! First off, this is awesome!

I might be missing something, but is it not possible right now to pass an API key with something other than an `access_token` param? I'm working with the HubSpot API, and although they claim you can authenticate with a param of `access_token`, it only seems to work when using the param `hapikey`.

Ideally I'd be able to store that just inside the `placid_tokens` list.

**Comment by seanwash** [comment]
Ok, so I just modified my copy of the plugin to look for an `hapikey` param, exactly how it looks for an `access_token` param now. Again, thanks for the awesome plugin! It's a pretty specific problem I have so Im not sure that it'll be useful to too many people, but let me know if you want a pull request.

**Comment by alecritson** [comment]
Hey @seanwash ,

Thanks for the feedback, good to hear you like using the plugin!

It was an interesting scenario you had and it kinda got me thinking it would be cool to be able to use tokens for any param, given some API's (like the one you have mentioned) sometimes use another name `token` could be used as well, for example.

So i've created a new [`develop`](https://github.com/alecritson/Placid-Statamic/tree/develop) branch on repo, i've just pushed some changes which you can have a go at testing with if you download from that branch and replace your current `placid` folder in your add ons.

So in your `placid.yaml` config file you would have

``` yaml
placid_tokens:
    hapikey_token: some-crazy-token
```

Then in your template you can do

```
{{ placid url="https://api.hubstop.com" query="hapikey:[hapikey_token]" }}
```

Notice we wrap `hapikey_token` within `[]`, this should tell placid you are looking for a config value in the `placid_tokens` and should swap out the value. Hopefully that'll work for you!

**Comment by seanwash** [comment]
Sounds great! I'll download it now and give it a shot.

**Comment by seanwash** [comment]
I gave it a try and it seems to be slowing the site down (including the admin) to a crawl. I also tried clearing the cache folder as well and the same thing happened. Once I put the old plugin folder back in and cleared out the cache it's working normally again. Sorry I don't have any more details for you, I'm in a hurry to get this project out the door.

let me know if I can do anything specific for debugging!

**Comment by alecritson** [comment]
Hey @sea wash

Sorry it's taken long to respond to this, but I've been using this method for various things now and I haven't noticed anything lagging or causing problems.

If do try again at any point to use this then if you look in the debug panel (on the page with the request) and should tell you how long placid took to resolve, for me it was a maximum of 4 seconds, depending on the api used.

Sorry I can't provide a fix at this point!

**Comment by alecritson** [comment]
Sorry my iPhone autocorrect your name...
