### ISSUE TITLE
Plans for v2 compatibility?

### ISSUE THREAD

**Issue by jackmcdade** [alecritson/Placid-Statamic#7]
Hey there, do you have plans to make this addon compatible with v2?

**Comment by alecritson** [comment]
Hey, 

I've just recently been familiarising myself with the new docs and how to get things transferred, but I will be starting to get it ready for v2 as soon as I can.

**Comment by jackmcdade** [comment]
Nice. Let us know if you need any pointers!

**Comment by alecritson** [comment]
I have released a beta update of the plugin for the new Statamic. It's on the `v2` (now default) branch.
