### ISSUE TITLE
Statamic can't load PlacidAPI

### ISSUE THREAD

**Issue by marconucara** [alecritson/Placid-Statamic#9]
Hi, I just switched to production server, but statamic can't load anymore the placid api.
I got this message:

FatalThrowableError in PlacidTags.php line 104:
Call to undefined method Statamic\Extend\Addon::request()
in PlacidTags.php line 104
at PlacidTags->request()
at call_user_func(array(object(PlacidTags), 'request')) in Engine.php line 162
at Engine::renderTag('placid', array('url' => '...

The results of `$this->api('placid')` at line 104 is not an instance of PlacidAPI class. So it seems that PlacidTags.php is loaded but PlacidAPI.php not.

All works fine in 2 other enviroments. Same php version (7.0.14) in one of them.

Any suggestion is realy appreciated,
thank you.

**Comment by marconucara** [comment]
I found the problem, you should write `$this->api('Placid')` with correct case at line 104 of PlacidTags.php. I do not know why it worked the other environment.

**Comment by alecritson** [comment]
Hey @nuky89 

Sorry it's taken a little while to reply.

I'm glad you've figured the issue out, thanks for reporting it, I'll be sure to get it fixed asap.
